name: Copy main.js
run-name: ${{ github.actor }} edited the main.js
on:
  push:
    branches:
      - main
    paths:
      - main.js
    tags-ignore:
      - "*"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'main.js'
          destination-username: 'KittenApps-Films'
          destination-repository: 'KittenApps-Films.github.io'
          #destination-directory: 'projects/my-project'
          commit-email: 'kittenappsandfilms@gmail.com'
